### ISSUE TITLE
Creating instances of a phantom_camera_2D.gd in code and allowing to set follow mode (e.g. via C#)

### ISSUE THREAD

**Issue by Shogan** [ramokz/phantom-camera#128]
### Project Type

2D

### Feature Description

Right now, I don't believe it is possible to create an instance of a Pcam group follow node in code - at least not easily. My use case is that I do everything in C#, but because a PCam cannot have it's follow mode changed at runtime, I cannot create an instance of a Pcam and set it to group follow. 

I can create the instance, but as there is no setter for follow mode, I can't do this programmatically.

```csharp
GDScript PhantomCamScriptResource = (GDScript)GD.Load("res://addons/phantom_camera/scripts/phantom_camera/phantom_camera_2D.gd");
GodotObject PhantomCamScriptInstance = (GodotObject)PhantomCamScriptResource.New(); // This is a GodotObject
PhantomCameraNode = PhantomCamScriptInstance as Node2D;

// no ability to Call set_follow_mode
// e.g. PhantomCameraNode.Call("set_follow_mode", enum_val_here);
```

I have had to kind of work around this by creating a phantom_camera_2D Node as a new scene (with it as the root), setup all the properties I need, and then instantiate the node from a `PackedScene`, adding it to my main scene. I already have a secondary Pcam, and I adjust priority at this point to allow the new Pcam to take over camera work.

I also need to append my nodes I want the camera to follow:

```csharp
foreach (var p in players)
{
   PhantomCameraNode.Call("append_follow_group_node", p);
}
```

With this workaround though, something odd happens - the new Pcam drifts off diagonally and does not follow the player nodes that were appended. (I confirmed they're appending by adding some extra logging into the append_follow_group_node function in the addon script).

I found that if, in the PackedScene (with Pcam2D as the root), I add an empty Node2D as a child of the Pcam, and then setup the Pcam with a single follow group node and pre-assign this empty child Node2D, then the follow group Pcam works as expected after instantiating the Pcam2D scene, and then appending the player nodes by code.

I'm not sure if at this stage this should be a bug request, or a new feature request, but I think it's the latter - basically have the ability to create a Pcam2D and set it up (e.g. follow mode, and other settings) by instantiating a new instance of it by code, whether in gdscript or C#.

Thanks!

### Use Cases

Instantiating a Pcam2D with group follow mode completely by code.

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

Often - a significant amount of projects can find this useful

### (Optional) Proposed Solution

Allow the Phantom Camera 2D node to dynamically switch follow modes by using a setter in code - (I'm not sure what the current limitations are against this, as the docs specifically mention its purposely not implemented, and that switching cams should be done by changing priority). 

Alternatively, using a Packed Scene pre-configured could be used a workaround, but the weirdness of the camera drifiting and not following nodes appended to the follow group could be fixed.

**Comment by ramokz** [comment]
Not being able to set a `Follow` mode via code was a design choice rather than a technical limitation. 

As doing so will significantly affect the logic behind a `PCam` that can lead to potential undesired results, be it strange positional outcomes or other unexpected logical weirdness, that would be tricky to adjust correctly during runtime. So the exclusion of that ability, and its consequent documentation note, is to discourage that pattern usage by virtue of not supporting it. The recommended approach, as you also mention, is to have an already predefined `PCam` with its `Follow` mode as opposed to instantiating a new one.

As a sidenote, a similar point was brought up in a Cinemachine forum thread with a [similar recommendation](https://forum.unity.com/threads/how-to-change-aim-and-body-via-script.692248/). I hadn't come across the post until just now, so it wasn't considered as part of the initial design choice here. The context there is also very likely not the same as yours, so it's not a silver bullet argument for me to make.

To that end, I'm not against adding the ability to set a `Follow`, or `Look At`, mode via code, but, again, the alternative approach you mentioned by using a `PackedScene` containing a `PCam` and then append the targets via code would the recommended approach.

Though, am not entirely sure how the drifting you mention happens. I've attached a small demo scene based on the aforementioned `PackedScene` pattern. That is, a `PackedScene` containing just a `PCam2D` with `Group` follow mode already set. The `PackedScene` then gets instantiated on load in a 2D scene via code, which then gets its follow targets appended using `append_follow_group_node_array()`. From the looks of it, it seems to behave as expected without having to do anything unusual.
[#128.zip](https://github.com/ramokz/phantom-camera/files/13232366/128.zip)

Out of curiosity, is there a reason why you're looking to instantiate the `PCam` via code, as opposed to having one idling in a scene and then apply the follow targets as needed? My only hunch would be for something entirely procedural?

**Comment by Shogan** [comment]
Thanks @ramokz for the demo project. I have been able to get things working using an instantiated scene with a Pcam setup how I need. The drifting appeared to be some weird node issues on my side that weren't correct.

The reason for doing this all by code (at least initially) was to do with the way my players in-game were setup while playing, and when out of the game. Now that you mention it, I think I could do this - have a lower priorty PCam setup idle in the scene, and when players are out of the game (dead), they can be added to the follow group in the idle camera, while the remaining in-game players stay in the active camera.

I was running into [0] index array issues inside the PCam .gdscript main logic when removing players that died - I spent some time trying to debug that, and think I eventually settled on the two-camera system above, and was instantiating one of them by code. Either way, I have two possible ways forward now, and am already up and running with the initial way I worked around this - thanks for the assistance!

In closing, I would say, don't implement anything to workaround the design decision you initially went with as it seems this was not an actual limitation that I ran into.
