### ISSUE TITLE
Jittery camera movement

### ISSUE THREAD

**Issue by HappyHeads** [ramokz/phantom-camera#173]
### Issue description

I have a 144hz monitor and camera movement is very jittery in 3D and 2D when I have VSync on or framerate cap at an odd number.  From my limited testing it seems to be an issue when the physics process happens at a different framerate compare to the monitors refresh rate. One way I found to solve the issue is to change `_process` inside phantom camera code to `_physics_process` but I'm not sure if there are any side effects to doing that. I know that physics jitter is a known issue with Godot itself but I wonder if there is specific ways to properly avoid it with phantom camera since its going to be a problem if players will have inconsistent framerate too.

### Steps to reproduce

* Have VSync or framerate cap turned on 
* Make sure that physics ticks per second is a different number that is not divisible by by your monitor refresh rate (for example if you have a 60hz monitor change the physics ticks per second to different number that is not divisible by 60) 
* Check one of the example scenes like `2DExampleScene.tscn` or `3DFollowSimpleExampleScene.tscn` for jitter when the character moves around

**Comment by ramokz** [comment]
Thanks for reporting this! This was an issue early on in the project, but had a hunch there were still things to do for this.

So have tested on both a 120hz and 60hz monitor.

Can't seem to replicate any jitter when V-Sync is enabled, or disabled, on either monitor — it has apparently been enabled for me the entire time. Not sure if the reason you're seeing it is due to having a higher refresh rate than me, though annoyingly can't check that.

But can see what you mean regarding the uneven / non-divisible by 60 `physics tick per second` value. The concern about `_physics_process` should only be for the `Camera2D/3D` itself, within the `PhantomCameraHost.gd`, which should ideally be kept in the `_process`.  The addon was initially using the `_physics_process` to move the `Camera2D/3D`, again, within `PhantomCameraHost.gd`. It was changed to only move in the `_process` after the `_physics_process` had run because it caused issues at certain monitor refresh rates, typically highers ones.

_However_, moving the `PhamtomCamera2D/3D` positional changes to the `_physics_process` does seem stable in any `physics tick per second` value when checking on both monitors and on two devices. So your suggestion seems like a valid solution to try out. If anything, it looks better than the existing one.

**Comment by ramokz** [comment]
I'll make a PR and try to gather some feedback for about a week or so.

If no one screams or shouts about it, I'll merge it in and submit an update.

**Comment by P5ina** [comment]
This is not a problem of phantom camera, you should tween your visuals in process. I have the same issue and I resolved it by using this [library](https://github.com/lawnjelly/smoothing-addon) (I found it on [godot's docs page](https://docs.godotengine.org/en/stable/tutorials/rendering/jitter_stutter.html)). But to work this with phantom camera you need to use my PR #179 that fixes camera being affected by `_physics_process`

**Comment by Lasuch69** [comment]
Mind that when using Third Person Mode, spring arm causes a bit of jitter too.

**Comment by ramokz** [comment]
Resolved in #179
