### ISSUE TITLE
Add a Picture-in-picture preview mode

### ISSUE THREAD

**Issue by Tarek-Hasan** [ramokz/phantom-camera#186]
### Project Type

2D, 3D

### Feature Description

Please add a Picture-in-picture preview mode, which is available in other game engines like, Unity and Unreal Engine.

<img width="1026" alt="screenshot" src="https://github.com/ramokz/phantom-camera/assets/27731012/62c396ea-eb6f-4afb-8290-a9453cc48926">

### Use Cases

With this feature, getting a camera preview will not take up too much display area.

### Importance

Medium - the feature would unlock new possibilities, but it's not a showstopper

### Usage

All the time - the feature can be very useful for a varity of different projects

### (Optional) Proposed Solution

Similar feature for godot is provided by a standalone addon called, [Little Camera Preview](https://github.com/anthonyec/godot_little_camera_preview). You may look into it.

**Comment by ramokz** [comment]
Not entirely sure what the ask is?

The `Little Camera Preview` already works nicely out of the box, as it just shows the currently selected `Camera3D` / `Camera2D` from the scene tree, and am not keen on replicating their addon for ethical reasons.

The only two things I can see that would make it integrate better would be to **A**) show the dead zone guides and **B**) allow for the preview to update when selecting a `PCam3D` or `PCam2D` node, but that's something even this plugin's `Viewfinder` doesn't do, so that's a new (and separate) suggestion in itself. But think the latter option isn't ideal since `PCams` are not cameras, so you would either need to teleport a `Camera` to it when you select it or instantiate a new `Camera`. Neither of which are ideal. This is also the intent behind the `Priority Override`, so that would solve that issue.

**Comment by JamesMWestbrook** [comment]
Yep the little camera plugin works. Youll have the option to pin it, and itll still work correctly off the Phantom Camera

**Comment by ramokz** [comment]
In addition to what was mentioned above, seeing how there was a recent tweet from the author of `Little Camera Preview` being remade in C++ with a suggestion of it being added to the main editor.

Am inclined to close this, as I don't see there being much value recreating the functionality when the other plugin exists and _might_ become native to Godot itself in the future.
