### ISSUE TITLE
f749b39 re-introduced jitter in dev_scene_2d

### ISSUE THREAD

**Issue by audeck** [ramokz/phantom-camera#283]
### Issue description

Not entirely sure why `_player_visuals` being top level matters here, but commit https://github.com/ramokz/phantom-camera/commit/f749b39d0b8261bae2199046e23619c4a592d001 introduces jitter into the default `dev_scene_2d` scene.

### Steps to reproduce

1. Clone the repository.
2. Setup a Godot project inside the repository folder.
3. Open `dev_scene_2d.tscn`.
4. Disable `follow_damping` on the active `PlayerPhantomCamera2D`.
5. Walk around.

**Comment by ramokz** [comment]
The `top level` bit is merely copying a function of what the [smoothing addon](https://github.com/lawnjelly/smoothing-addon/blob/3.x/addons/smoothing/smoothing_2d.gd) does. It essentially just means that it further decouples the visual node from the physics node's movement.

I removed it because there was a strange bug where the visual node would have its position reset to `Vector2(0, 0)` on the first frame before going to its intended position. The issue that causes is that the damping `PCam2D` would move from that reset position to the actual position when running the game — i.e. the camera would trigger a pseudo-tween on start-up.

If you add `_player_visuals.top_level = true` to the `_ready()` function in the `CharacterBody2D` script, then on the `PCam2D` itself enable the damping, with a potentially increased amount, you should see the issue happening. This seems to only be occurring in 2D scenes, so my gut feeling says that it is likely an engine bug, but I am not sure.

Wanted to have damping on by default in the example scene, but also wanted to avoid that weird effect/bug, so stripped out the `top level` assignment as a result. Not ideal, but wanted it to look nice out of the box whilst trying to figure out what might be causing the issue.

**Comment by ramokz** [comment]
Seems to be solved in Godot 4.3

**Comment by ramokz** [comment]
Readded in the `0.7.1` branch.
