### ISSUE TITLE
PC Host error: "Nonexistent function 'get_global_transform' in base 'Nil'.`

### ISSUE THREAD

**Issue by Matt-Murch** [ramokz/phantom-camera#317]
### Issue description

Having a Phantom Camera Host in any scene causes constant error to be output:
`  res://addons/phantom_camera/scripts/phantom_camera_host/phantom_camera_host.gd:252 - Invalid call. Nonexistent function 'get_global_transform' in base 'Nil'.`

I've tried with and without a phantom camera in the scene and it has the same result. 

### Steps to reproduce

Add phantom camera to project
Add a camera 3D to scene
Add a Phantom Camera Host as a child of the camera 3D

or

Add phantom camera to project
Add a Phantom Camera Host to scene

### (Optional) Minimal reproduction project

[PCHErrorReproduction.zip](https://github.com/user-attachments/files/15524301/PCHErrorReproduction.zip)

**Comment by cryoboltinteractive** [comment]
Facing the same issue, Reverting back to the old version for now. Seems like an issue contained into the Host only.
Hot Fix
![image](https://github.com/ramokz/phantom-camera/assets/157096256/64ea1e6a-a8cd-4490-a551-d2aaf60ef1ea)

**Comment by ramokz** [comment]
Thanks for the report and the reproduction project!
I can see what you mean.

Normally, I would release a hotfix for this; however, this should already be fixed in the [0.7.2](https://github.com/ramokz/phantom-camera/blob/ff78d2153865ff3e8d0d26591a4f44c0bcfa4491/addons/phantom_camera/scripts/phantom_camera_host/phantom_camera_host.gd#L320) branch as part of wider internal changes, and seeing this only spams errors and doesn't break anything, I'm inclined to leave it be for now.

Expecting to release 0.7.2 within the next week or so.

![image](https://github.com/ramokz/phantom-camera/assets/5159399/037453a4-ab60-4375-a729-feaed3c2cd81)

**Comment by Matt-Murch** [comment]
Awesome, looking forward to the 0.7.2 release! Thanks for looking into it
