### ISSUE TITLE
Tweening of FOV/Near/Far properties ends on incorrect values

### ISSUE THREAD

**Issue by NullShock78** [ramokz/phantom-camera#326]
### Issue description

When tweening between two `PhantomCamera3D`s with different FOV/Near/Far settings, the final values are not equal to the ones defined in the target's `Camera3DResource`

### Steps to reproduce

1. Have a Camera3D with a `PhantomCameraHost`, and two `PhantomCamera3D` nodes with different FOV/Near/Far settings in their `Camera3DResource`s
2. Activate a tween between the two `PhantomCamera3D`s
3. After the tween finishes, go into the Remote scene tree and compare the FOV/Near/Far values on the `Camera3D` node to what is defined in the current `PhantomCamera3D`'s `Camera3DResource`.

**Comment by ramokz** [comment]
I can't seem to replicate the issue.

`Camera3DResource` for `PlayerPCam`:
- fov: `75`
- near: `0.05`
- far: `2000`

`Camera3DResource` for `ScenePCam`:
- fov: `10`
- near: `0.08`
- far: `6000`

https://github.com/ramokz/phantom-camera/assets/5159399/188a16e9-7446-4f01-b69f-369869aad626

**Comment by NullShock78** [comment]
Uploaded a minimal example [project](https://github.com/NullShock78/TweenIssueExample)
Might be framerate dependent, so max fps is set in the project

**Comment by ramokz** [comment]
The issue seems to partially stem from setting the priority in the `_ready()` of the root node.
If you replace the `PhantomCameraHost.gd` file with the version below, then that should resolve it.
It basically boils down to always running the last frame, which it sometimes skips — likely due to the fluctuating delta value.

[phantom_camera_host.gd.zip](https://github.com/user-attachments/files/15828283/phantom_camera_host.gd.zip)
