### ISSUE TITLE
Case mismatch error when opening a project

### ISSUE THREAD

**Issue by Burloe** [ramokz/phantom-camera#339]
### Issue description

Since 7.x, I've been getting this error in regards to the new naming convention from "x_2D" to "x_2d". I followed the steps provided in the link when I updated but now, it's telling me that it wont find the old files. 

I did experience #323 and tried a bunch of fixes. But I also did a clean reinstall at one point and still have this. Using 7.2.1.
![image](https://github.com/ramokz/phantom-camera/assets/128168396/85a8a3b0-8699-4d2f-808b-0b712293e5fe)

### Steps to reproduce

Including the phantom_camera folder from the project. Let me know if anything else is needed.  

### (Optional) Minimal reproduction project

[phantom_camera.zip](https://github.com/user-attachments/files/15944469/phantom_camera.zip)

**Comment by ramokz** [comment]
This is a computer-by-computer / project-by-project issue, annoyingly, and so the addon version you shared works fine for.

![image](https://github.com/ramokz/phantom-camera/assets/5159399/483b386a-3ac1-4886-9f74-7007bad9b035)

---

It's generally due to a Godot caching thing where it stores the class names reference but isn't too keen on updating them.
Have you tried using either an IDE, or another type editor, and looked through any instances of the uppercased class name variants? Specifically, within hidden files both in the project itself and the parent directory.

**Comment by Burloe** [comment]
> Have you tried using either an IDE, or another type editor, and looked through any instances of the uppercased class name variants? Specifically, within hidden files both in the project itself and the parent directory.

I've only done it manually and with Godot but I just tried it with VSC and found some cases of it. I changed it, reloaded but I'm still getting the error. Maybe it's better to just make a new project and import everything fresh. It doesn't appear in a fresh project so what you say seems like it's the case.

**Comment by ramokz** [comment]
You could.
But if you're not running into any issues with it, and it's just logging the warning output, then you could also keep working in your current project. There's a chance that Godot might update the cached file name with the new one at some point — though, obviously, that's not a guarantee.

**Comment by Burloe** [comment]
I see. I've contemplated doing it regardless due to issues with other addons and stuff so this is a good excuse to do it. 

I appreciate the quick help and thanks for making this plugin by the way! I'm closing this issue since this is more of a Godot issue rather than an issue with PCam.
