### ISSUE TITLE
Persistent error - get_tree: Parameter "data.tree" is null.

### ISSUE THREAD

**Issue by witchpiggie** [ramokz/phantom-camera#377]
### Issue description

Receive this error when using PhantomCamera 0.7.3 in Godot 4.3
get_tree: Parameter "data.tree" is null. <C++ Source>   ./scene/main/node.h:446 @ get_tree()

### Steps to reproduce

- Create Project
- AssetLib -> Install Phantom Camera 0.7.3
- Project Settings -> Enable Phantom Camera
- Add a Node2D
- Add a 2D Camera to the root Node2D
- Add a PhantomCameraHost as a child of the camera
- Add a 2D PhantomCamera to the root Node2D

### (Optional) Minimal reproduction project

[min.project.zip](https://github.com/user-attachments/files/16860528/min.project.zip)

**Comment by jktrctt** [comment]
I've been having this same issue with my project for weeks after upgrading to 4.3. It's kind of driving me nuts.

**Comment by ValFan771** [comment]
For me it is even weirder. I added the addon to my project but I did not yet configure any cameras nor added a PhantomCameraHost to my scene yet I still get the error message during godot startup or when launching the project itself.

When I try to disable the autoload plugin in the project settings I am still getting the error. 
The project itself works fine, just as Jktrctt said, it is slightly concerning.

**Comment by hunterloftis** [comment]
Here's a minimal reproduction with a totally-vanilla Godot 4.3 project, no need for PhantomCamera or any other changes. It seems to be triggered by setting physics interpolation to `Off` on any `Camera2D`.

Upon opening the project:
![image](https://github.com/user-attachments/assets/5d0b9c41-9384-4078-af1a-26ee42e6e5a7)

Upon starting the scene:
![image](https://github.com/user-attachments/assets/b204190a-a38d-45da-8627-1da294342005)

[bug_cam_physics.zip](https://github.com/user-attachments/files/17284872/bug_cam_physics.zip)

**Comment by ramokz** [comment]
> It seems to be triggered by setting physics interpolation to Off on any Camera2D.

That seems to be it, yes!

It's very weird, since the error code in the editor points to it being a null pointer issue when looking up the line in `node.h` in Godot's source code. Looked and tested around for a while, but could never figure out where it would have come from. Seems to have been a red herring this whole time…

So the good news is that removing the error is pretty trivial, basically just changing a number in the `PCamHost` file, however the less good news is that it now produces a persistent warning instead:
![image](https://github.com/user-attachments/assets/e5a8e2f8-848a-4b15-8ff1-423310504427)

Looking through the engine source code, and doing a few tests, it seems like there isn't really a way to avoid this one as it appears to be triggered whenever `physics interpolation` is enabled from the `Project Settings` — happy to be proven wrong though!

For those wanting a quick DIY fix before the next release, you can just update the value from `2` to `0` on line `486` inside `phantom_camera_host.gd`:
```gdscript
# camera_2d.set("physics_interpolation_mode", 2)
camera_2d.set("physics_interpolation_mode", 0)
```
